name: CI

on:
  push:
  pull_request:

jobs:
  build-phar:
    name: Build PHAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - name: Download Box
        run: wget https://github.com/box-project/box/releases/download/3.13.0/box.phar

      - name: Compile PHAR
        run: php box.phar compile

      - uses: actions/upload-artifact@v1
        name: Upload the PHAR artifact
        with:
          name: phpmyadmin.phar
          path: bin/phpmyadmin.phar

  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 8.0
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

  cs-check:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          coverage: none
          tools: php-cs-fixer

      - name: Check CS
        run: php-cs-fixer fix --dry-run --diff
